name: math_ext
description: Geographic math module
version: 2.0.2
publisher: swkim@lbstech.net
repository: https://github.com/LBSTECH/math_ext

environment:
  sdk: ">=2.14.4 <4.0.0"

dependencies:
  vector_math: ^2.1.2

dev_dependencies:
  lints: ">=1.0.1 <2.0.0"
